version: "1"
services:
  app:
    container_name: app
    restart: always
    build: ./path/to/your/dockerfile/root
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"